---
- name: Load merge a configuration to a device running Junos OS
  hosts: ALL
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: Checking NETCONF connectivity
     wait_for: host={{ inventory_hostname }} port=830  timeout=5